---
consent:
  version: 1
  author: ddp
  id: ehive-cppd-2__case
  lang: en
fonts:
  default: Helvetica
options:
  width: 10.0
  height: 10.0
  inputs:
    - page: 2
      yes:
        x: 224.00
        y: 470.00
      no:
        x: 300.00
        y: 470.00
    - page: 2
      yes:
        x: 92.00
        y: 425.00
      no:
        x: 1000.00 # Push NO off the page
        y: 425.00
    - page: 2
      yes:
        x: 172.00
        y: 425.00
      no:
        x: 1000.00 # Push NO off the page
        y: 425.00
signing:
  name:
    page: 9
    x: 238
    y: 548
    fontSize: 12
    maxWidth: 152
  date:
    page: 9
    x: 418
    y: 548
    fontSize: 12
    format: "MM.dd.yyyy   HH:mm 'UTC'"
  signature:
    page: 9
    x: 58
    y: 548
    maxWidth: 153
    maxHeight: 30
