---
consent:
  version: 1
  author: ddp
  id: ehive-cramp
  lang: en
fonts:
  default: Helvetica
options:
  width: 10.0
  height: 10.0
  inputs:
    # Consent to Recontacting
    - page: 4
      yes:
        x: 224.00
        y: 330.00
      no:
        x: 300.00
        y: 330.00
    # Contact by Email
    - page: 4
      yes:
        x: 93.00
        y: 284.00
      no:
        x: 1000.00 # Push NO off the page
        y: 284.00
    # Contact by Phone
    - page: 4
      yes:
        x: 173.00
        y: 284.00
      no:
        x: 1000.00 # Push NO off the page
        y: 284.00
    # Contact by Letter
    - page: 4
      yes:
        x: 248.00
        y: 284.00
      no:
        x: 1000.00 # Push NO off the page
        y: 284.00
      # Contact by Text
    - page: 4
      yes:
        x: 332.00
        y: 284.00
      no:
        x: 1000.00 # Push NO off the page
        y: 284.00
signing:
  name:
    page: 11
    x: 238
    y: 558
    fontSize: 12
    maxWidth: 152
  date:
    page: 11
    x: 418
    y: 558
    fontSize: 12
    format: "MM.dd.yyyy   HH:mm 'UTC'"
  signature:
    page: 11
    x: 58
    y: 558
    maxWidth: 153
    maxHeight: 30
