---
consent:
  version: 1
  author: ddp
  id: ehive-warrior-shield
  lang: en
fonts:
  default: Helvetica
signing:
  name:
    page: 9
    x: 238
    y: 172
    fontSize: 14
    maxWidth: 152
  date:
    page: 9
    x: 418
    y: 172
    fontSize: 14
    # maxWidth: 60
    format: MM.dd.yyyy
  signature:
    page: 9
    x: 58
    y: 172
    maxWidth: 153
    maxHeight: 30
