---
consent:
  version: 1
  author: ddp
  id: ehive-pss
  lang: en
fonts:
  default: Helvetica
options:
  width: 12.25 # width of the X in the PDF. Should be the same as height to be square
  height: 12.25
  inputs:
    - page: 2
      yes: # location of the X for the Yes answer
        x: 95.00
        y: 458.00
      no: # location of the X for the No answer
        x: 175.00
        y: 458.00
signing:
  name:
    fontSize: 26
    page: 9 # just because that example pdf has only 10 pages
    x: 62
    y: 250
    maxWidth: 270
  date:
    fontSize: 26
    page: 9 # just because that example pdf has only 10 pages
    x: 300
    y: 250
    format: MM.dd.yyyy
  signature:
    page: 9 # just because that example pdf has only 10 pages
    x: 62
    y: 150
    maxWidth: 200
    maxHeight: 80
