---
consent:
  version: 1
  author: ddp
  id: ehive-digi-ibd-001
  lang: en
fonts:
  default: Helvetica
signing:
  name:
    page: 7
    x: 238
    y: 570
    fontSize: 12
    maxWidth: 152
  date:
    page: 7
    x: 418
    y: 570
    fontSize: 12
    # maxWidth: 60
    format: MM.dd.yyyy
  signature:
    page: 7
    x: 58
    y: 570
    maxWidth: 153
    maxHeight: 30
