---
consent:
  version: 1
  author: ddp
  id: ehive-digi-ibd-001
  lang: en
fonts:
  default: Helvetica
options:
  width: 12.25
  height: 12.25
  inputs:
    - page: 2
      yes:
        x: 95.00
        y: 485.00
      no:
        x: 175.00
        y: 485.00
signing:
  name:
    fontSize: 26
    page: 9
    x: 62
    y: 535
    maxWidth: 270
  date:
    fontSize: 26
    page: 9
    x: 300
    y: 535
    format: MM.dd.yyyy
  signature:
    page: 9
    x: 62
    y: 535
    maxWidth: 200
    maxHeight: 80
