---
consent:
  version: 1
  author: ddp
  id: ehive-playground
  lang: en
fonts:
  default: Helvetica
options:
  width: 10.0
  height: 10.0
  inputs:
    # Consent to Recontacting
    - page: 1
      yes:
        x: 224.00
        y: 330.00
      no:
        x: 300.00
        y: 330.00
    # Contact by Email
    - page: 1
      yes:
        x: 92.25
        y: 284.00
      no:
        x: 1000.00 # Push NO off the page
        y: 284.00
    # Contact by Phone
    - page: 1
      yes:
        x: 171.75
        y: 284.00
      no:
        x: 1000.00 # Push NO off the page
        y: 284.00
    # Contact by Letter
    - page: 1
      yes:
        x: 249.25
        y: 284.00
      no:
        x: 1000.00 # Push NO off the page
        y: 284.00
      # Contact by Text
    - page: 1
      yes:
        x: 332.50
        y: 284.00
      no:
        x: 1000.00 # Push NO off the page
        y: 284.00
signing:
  name:
    page: 1
    x: 238
    y: 300
    fontSize: 12
    maxWidth: 152
  date:
    page: 1
    x: 418
    y: 300
    fontSize: 12
    format: "MM.dd.yyyy   HH:mm 'UTC'"
  signature:
     page: 1
     x: 58
     y: 300
     maxWidth: 153
     maxHeight: 30
